const state={project:null,requests:[],csvText:"",mechanism:null,mcmc:null,pendingDraft:null,chatSession:sessionStorage.getItem('cigp_chat_session')||null};
const titles={chat:"与动力学 Agent 对话",project:"定义反应项目",experiments:"规划动力学实验",quality:"验证实验数据",mechanism:"编译候选机理",mcmc:"评估机理后验",cigp:"主动学习优化"};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function notify(message,error=false){const n=$("#notice");n.textContent=message;n.className=`notice show${error?" error":""}`;setTimeout(()=>n.classList.remove("show"),5000)}
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||`HTTP ${response.status}`);return body}
function setStage(stage){$("#stage").textContent=(stage||"intake").toUpperCase()}
function navigate(page){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));$("#page-title").textContent=titles[page]}
$$('.nav-item').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.page)));
function formula(text){const atoms={};for(const match of text.matchAll(/([A-Z][a-z]?)(\d*)/g))atoms[match[1]]=(atoms[match[1]]||0)+Number(match[2]||1);return atoms}
function formulaText(atoms={}){return Object.entries(atoms).map(([element,count])=>element+(count===1?'':count)).join('')}
function addMessage(role,content,extraClass=''){const box=$("#chat-messages");const item=document.createElement('div');item.className=`message ${role} ${extraClass}`;item.innerHTML=`<span>${role==='user'?'你':'Agent'}</span><p></p>`;item.querySelector('p').textContent=content;box.appendChild(item);box.scrollTop=box.scrollHeight;return item}
$("#chat-form").addEventListener("submit",async event=>{event.preventDefault();const input=$("#chat-input");const message=input.value.trim();if(!message)return;addMessage('user',message);input.value='';const thinking=addMessage('assistant','正在理解反应目标并检查缺失信息…','thinking');try{const result=await api('/api/chat',{method:'POST',body:JSON.stringify({message,session_id:state.chatSession,project_context:state.project})});thinking.remove();state.chatSession=result.session_id;sessionStorage.setItem('cigp_chat_session',result.session_id);addMessage('assistant',result.reply);if(result.project_draft){state.pendingDraft=result.project_draft;$("#draft-summary").textContent=`${result.project_draft.title||'反应项目'} · ${(result.missing_information||[]).length}项信息待确认`;$("#draft-card").classList.remove('hidden')}if(result.missing_information?.length)notify(`仍需确认：${result.missing_information.join('、')}`)}catch(error){thinking.remove();addMessage('assistant',`请求失败：${error.message}`);notify(error.message,true)}});
$("#apply-draft-btn").addEventListener("click",()=>{const p=state.pendingDraft;if(!p)return;const form=$("#project-form");form.elements.project_id.value=p.project_id||`reaction_${Date.now()}`;form.elements.title.value=p.title||'';form.elements.objective.value=p.objective||'combined';form.elements.request.value=p.raw_user_request||'';form.elements.reactant.value=p.reactants?.[0]?.name||'';form.elements.reactant_formula.value=formulaText(p.reactants?.[0]?.formula);form.elements.product.value=p.known_products?.[0]?.name||'';form.elements.product_formula.value=formulaText(p.known_products?.[0]?.formula);navigate('project');notify('项目草案已填入表单，请检查后创建')});
$("#project-form").addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));const payload={project_id:data.project_id,title:data.title,objective:data.objective,raw_user_request:data.request,reactants:[{name:data.reactant,formula:formula(data.reactant_formula),role:"reactant"}],known_products:[{name:data.product,formula:formula(data.product_formula),role:"product"}],observed_variables:[{species:data.reactant},{species:data.product}]};try{const result=await api('/api/projects',{method:'POST',body:JSON.stringify(payload)});state.project=result.project;setStage(state.project.stage);$("#project-result").textContent=`已创建 ${state.project.project_id}`;$("#node-a").textContent=data.reactant;$("#node-p").textContent=data.product;seedMechanism();notify('项目已创建，下一步可以生成实验计划');navigate('experiments')}catch(error){notify(error.message,true)}});
$("#ai-parse-btn").addEventListener("click",async()=>{const form=$("#project-form");const data=Object.fromEntries(new FormData(form));try{notify('正在用LLM解析反应描述');const result=await api('/api/llm/parse-project',{method:'POST',body:JSON.stringify({project_id:data.project_id,user_request:data.request})});const p=result.project;form.elements.title.value=p.title;form.elements.objective.value=p.objective;form.elements.reactant.value=p.reactants[0]?.name||'';form.elements.reactant_formula.value=Object.entries(p.reactants[0]?.formula||{}).map(([e,n])=>e+(n===1?'':n)).join('');form.elements.product.value=p.known_products[0]?.name||'';form.elements.product_formula.value=Object.entries(p.known_products[0]?.formula||{}).map(([e,n])=>e+(n===1?'':n)).join('');notify('LLM解析完成，请检查后再创建项目')}catch(error){notify(error.message,true)}});
$("#plan-btn").addEventListener("click",async()=>{if(!state.project)return notify('请先创建项目',true);try{const result=await api(`/api/projects/${state.project.project_id}/experiment-plan`,{method:'POST',body:'{}'});state.project=result.project;state.requests=result.requests;setStage(state.project.stage);$("#experiment-count").textContent=state.requests.length;$("#time-count").textContent=state.requests[0]?.sampling_times.length||0;$("#experiment-table").innerHTML=state.requests.map(r=>`<tr><td><b>${r.experiment_id}</b></td><td>${r.purpose}</td><td>${r.variables.temperature_K||'—'}</td><td>${r.sampling_times.length}</td><td>${r.rationale}</td></tr>`).join('');notify('实验计划已生成，CSV模板已保存在项目目录')}catch(error){notify(error.message,true)}});
$("#csv-file").addEventListener("change",async event=>{const file=event.target.files[0];if(file){state.csvText=await file.text();event.target.nextElementSibling.querySelector('b').textContent=file.name;event.target.nextElementSibling.querySelector('span').textContent=`${Math.round(file.size/1024)} KB · 已在本地读取`}});
$("#validate-btn").addEventListener("click",async()=>{if(!state.project)return notify('请先创建项目',true);if(!state.csvText)return notify('请选择CSV文件',true);try{const result=await api(`/api/projects/${state.project.project_id}/datasets/validate`,{method:'POST',body:JSON.stringify({csv_text:state.csvText})});state.project=result.project;setStage(state.project.stage);$("#validation-state").textContent='数据有效';$("#validation-list").innerHTML=`<li>已读取 ${result.row_count} 行</li>${Object.entries(result.report.species_coverage).map(([k,v])=>`<li>${k} 覆盖率 ${(v*100).toFixed(0)}%</li>`).join('')}`;$("#risk-list").innerHTML=result.report.identifiability_risks.map(x=>`<p>${x}</p>`).join('')||'<p>未发现基础可辨识性风险</p>';notify('数据验证通过，可以准备候选机理');navigate('mechanism')}catch(error){$("#validation-state").textContent='验证失败';notify(error.message,true)}});
function seedMechanism(){if(!state.project)return;const a=state.project.reactants[0],p=state.project.known_products[0];const intermediate={name:'I',formula:a.formula,status:'llm_candidate',role:'intermediate'};$("#mechanism-json").value=JSON.stringify({mechanism_id:'candidate_v001',project_id:state.project.project_id,species:[a,intermediate,p],steps:[{step_id:'formation',reactants:{[a.name]:1},products:{I:1},rate_law_family:'arrhenius',prior_probability:.2,evidence:'user/agent candidate'},{step_id:'conversion',reactants:{I:1},products:{[p.name]:1},rate_law_family:'arrhenius',prior_probability:.2,evidence:'user/agent candidate'}],approved:false},null,2)}
$("#ai-mechanism-btn").addEventListener("click",async()=>{if(!state.project)return notify('请先创建项目',true);try{notify('正在生成候选基元反应');const result=await api('/api/llm/propose-mechanism',{method:'POST',body:JSON.stringify({project:state.project,dataset_summary:{stage:state.project.stage}})});state.mechanism=result.mechanism;$("#mechanism-json").value=JSON.stringify(result.mechanism,null,2);notify('LLM候选已生成，必须编译检查并由你批准')}catch(error){notify(error.message,true)}});
$("#compile-btn").addEventListener("click",async()=>{try{const payload=JSON.parse($("#mechanism-json").value);const result=await api(`/api/projects/${state.project.project_id}/mechanisms/register`,{method:'POST',body:JSON.stringify(payload)});state.mechanism=payload;state.project=result.project;setStage(state.project.stage);$("#compile-result").textContent=`编译通过 · ${result.report.species_order.length} 个物种 · ${result.report.parameter_names.length} 个动力学参数`;notify('候选机理已注册，等待人工批准');navigate('mcmc')}catch(error){$("#compile-result").textContent=`编译失败：${error.message}`;notify(error.message,true)}});
$("#mcmc-btn").addEventListener("click",async()=>{if(!state.mechanism)return notify('请先编译候选机理',true);try{$("#mcmc-state").textContent='计算中';$("#mcmc-message").textContent='正在运行短链演示，正式研究应增加步数和链数。';const approved=await api(`/api/projects/${state.project.project_id}/mechanisms/approve`,{method:'POST',body:JSON.stringify(state.mechanism)});state.mechanism=approved.mechanism;const result=await api(`/api/projects/${state.project.project_id}/mcmc/run`,{method:'POST',body:JSON.stringify({mechanism:state.mechanism,sources:[state.project.reactants[0].name],targets:[state.project.known_products[0].name],config:{n_steps:80,burn_in:20,n_chains:2}})});state.project=result.project;state.mcmc=result.summary;setStage(state.project.stage);const values=Object.values(state.mcmc.reaction_pip);$("#pip-chart").innerHTML=values.map(v=>`<i style="height:${Math.max(3,v*100)}%"></i>`).join('');$("#pip-label").textContent=Object.entries(state.mcmc.reaction_pip).map(([k,v])=>`${k} ${(v*100).toFixed(0)}%`).join(' · ');$("#rhat").textContent=Number(state.mcmc.posterior_predictive_metrics.rhat_max).toFixed(3);$("#ess").textContent=Number(state.mcmc.posterior_predictive_metrics.ess_min).toFixed(1);$("#rmse").textContent=Number(state.mcmc.posterior_predictive_metrics.map_rmse).toPrecision(3);$("#path-count").textContent=Object.keys(state.mcmc.pathway_pip).length;$("#mcmc-state").textContent=state.mcmc.converged?'收敛通过':'需要更多采样';$("#mcmc-message").textContent=state.mcmc.identifiability_warnings.join(' ')||'可以进入CIGP阶段';notify('PC-MCMC试运行完成')}catch(error){$("#mcmc-state").textContent='运行失败';$("#mcmc-message").textContent=error.message;notify(error.message,true)}});
async function restoreChat(){if(!state.chatSession)return;try{const result=await api(`/api/chat/${state.chatSession}`);if(result.messages.length){$("#chat-messages").innerHTML='';result.messages.forEach(row=>addMessage(row.role,row.content));const last=[...result.messages].reverse().find(row=>row.role==='assistant'&&row.metadata?.project_draft);if(last){state.pendingDraft=last.metadata.project_draft;$("#draft-summary").textContent=state.pendingDraft.title||'反应项目草案';$("#draft-card").classList.remove('hidden')}}}catch(_error){sessionStorage.removeItem('cigp_chat_session');state.chatSession=null}}
async function bootstrap(){try{await api('/api/health');const llm=await api('/api/llm/status');$("#api-label").textContent=llm.configured?`${llm.model} · 已配置`:'LLM API 未配置';const templates=await api('/api/templates');$("#template-list").innerHTML=templates.templates.map(t=>`<span title="${t.inputs.join(', ')}">${t.name}</span>`).join('');await restoreChat()}catch(error){notify('本地服务未连接，请通过 run_agent_web.py 启动',true)}}bootstrap();
